package mini.projet.BO;
// Generated Mar 29, 2020 10:43:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private Integer idAddress;
     private Client client;
     private String ville;
     private String pays;
     private String rue;
     private int maison;
     private Set commandes = new HashSet(0);

    public Address() {
    }

	
    public Address(String ville, String pays, String rue, int maison) {
        this.ville = ville;
        this.pays = pays;
        this.rue = rue;
        this.maison = maison;
    }
    public Address(Client client, String ville, String pays, String rue, int maison, Set commandes) {
       this.client = client;
       this.ville = ville;
       this.pays = pays;
       this.rue = rue;
       this.maison = maison;
       this.commandes = commandes;
    }
   
    public Integer getIdAddress() {
        return this.idAddress;
    }
    
    public void setIdAddress(Integer idAddress) {
        this.idAddress = idAddress;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getPays() {
        return this.pays;
    }
    
    public void setPays(String pays) {
        this.pays = pays;
    }
    public String getRue() {
        return this.rue;
    }
    
    public void setRue(String rue) {
        this.rue = rue;
    }
    public int getMaison() {
        return this.maison;
    }
    
    public void setMaison(int maison) {
        this.maison = maison;
    }
    public Set getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Set commandes) {
        this.commandes = commandes;
    }




}


