package mini.projet.BO;
// Generated Mar 29, 2020 10:43:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private Integer idCat;
     private String label;
     private String description;
     private Set productses = new HashSet(0);

    public Categories() {
    }

	
    public Categories(String label) {
        this.label = label;
    }
    public Categories(String label, String description, Set productses) {
       this.label = label;
       this.description = description;
       this.productses = productses;
    }
   
    public Integer getIdCat() {
        return this.idCat;
    }
    
    public void setIdCat(Integer idCat) {
        this.idCat = idCat;
    }
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }




}


