package mini.projet.BO;
// Generated Mar 29, 2020 10:43:27 PM by Hibernate Tools 4.3.1
/**
 * Commande generated by hbm2java
 */
public class Commande  implements java.io.Serializable {


     private Integer idCommade;
     private Address address;
     private Client client;
     private Products products;
     private String etat;
     private int qte;

    public Commande() {
    }

	
    public Commande(Address address, Products products, String etat, int qte) {
        this.address = address;
        this.products = products;
        this.etat = etat;
        this.qte = qte;
    }
    public Commande(Address address, Client client, Products products, String etat, int qte) {
       this.address = address;
       this.client = client;
       this.products = products;
       this.etat = etat;
       this.qte = qte;
    }
   
    public Integer getIdCommade() {
        return this.idCommade;
    }
    
    public void setIdCommade(Integer idCommade) {
        this.idCommade = idCommade;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }
    public int getQte() {
        return this.qte;
    }
    
    public void setQte(int qte) {
        this.qte = qte;
    }




}


